"""user_facts_added

Revision ID: 914b45893bc6
Revises: d1ff1e3595ac
Create Date: 2025-11-16 01:03:07.049619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '914b45893bc6'
down_revision: Union[str, Sequence[str], None] = 'd1ff1e3595ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_facts_fact_id'), 'user_facts', ['fact_id'], unique=False)
    op.create_index(op.f('ix_user_facts_id'), 'user_facts', ['id'], unique=False)
    op.create_index(op.f('ix_user_facts_user_id'), 'user_facts', ['user_id'], unique=False)

    # Add columns with server_default to handle existing rows
    op.add_column('facts', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('facts', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('facts', 'updated_at')
    op.drop_column('facts', 'created_at')
    op.drop_index(op.f('ix_user_facts_user_id'), table_name='user_facts')
    op.drop_index(op.f('ix_user_facts_id'), table_name='user_facts')
    op.drop_index(op.f('ix_user_facts_fact_id'), table_name='user_facts')
    op.drop_table('user_facts')
    # ### end Alembic commands ###
