"""User ID Added To Facts Table

Revision ID: a762a07b300a
Revises: 914b45893bc6
Create Date: 2025-11-16 02:35:29.897509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a762a07b300a'
down_revision: Union[str, Sequence[str], None] = '914b45893bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('facts', sa.Column('is_created_by_llm', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_facts_user_id'), 'facts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'facts', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('uix_user_fact', 'user_facts', ['user_id', 'fact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_fact', 'user_facts', type_='unique')
    op.drop_constraint(None, 'facts', type_='foreignkey')
    op.drop_index(op.f('ix_facts_user_id'), table_name='facts')
    op.drop_column('facts', 'is_created_by_llm')
    op.drop_column('facts', 'user_id')
    # ### end Alembic commands ###
